---
- name: update apt cache
  apt: update_cache=true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_os_family == "Debian"

- name: update yum cache
  yum:
      name: '*'
      update_cache: true
      enablerepo: '{{ repository|replace("/", "_") }}'
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_os_family == "RedHat"
